#3 user entity 생성
choorai/retrospect-backend pull request #4
Opened 2024-08-11 10:57 UTC by JoungMinJu

#3 

User Entity를 생성했습니다.

- @Entity 생성
- flyway 설정
- migration 파일 작성 (V년월일_시분__이름.sql 형식)

2024-08-13 05:32 UTC, seokhwan-an reviewed
민주님 user entity를 구성하시느라 고생하셨습니다👍👍
수정했으면 하는 부분에 리뷰 남겼습니다!

2024-08-13 05:32 UTC, seokhwan-an commented on src/main/java/choorai/retrospect/user/entity/User.java
> +public class User {
현재 User 테이블에는 db에서 식별할 수 있게 
```java
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
```
위의 컬럼을 추가하는 것이 좋을 것 같습니다!

2024-08-13 05:32 UTC, seokhwan-an commented on src/main/java/choorai/retrospect/user/entity/User.java
> +    private String companyName;
이 부분은 현재 db에서만 length 검증이 이루어지는데 객체 상태에서도 해당 검증을 할 수 있게 각 column을 객체로 관리하면 좋을 것 같습니다! (null 체크도 같이 해주시면 좋을 것 같습니다)

2024-08-13 05:32 UTC, seokhwan-an commented on src/main/java/choorai/retrospect/user/entity/User.java
> +public class User {
지금 보니 user_id로 식별을 하시려고 했군요 
현재상황이 유지되면 user 상세 조회를 할 때에는 user_id로 해야하는데 이 때 해당 정보가 url에 담겨서 오는 것은 좋은 방법이지 않을 것 같아서 위의 제시한 컬럼을 추가해주면 좋을 것 같습니다!

2024-08-17 20:14 UTC, xi-jjun commented on src/main/java/choorai/retrospect/user/entity/User.java
> +    private String companyName;
특별한 이유가 있는게 아니라면, varchar의 길이를 함부로 제한하는 것은 바람직하지 않을 수 있습니다.
DB 변경사항은 코드 작업보다 힘든 일이기에 웬만하면 기본값을 쓰는 방향으로 가면 좋을 것 같습니다.

2024-08-17 20:18 UTC, xi-jjun reviewed
PR에는 최대한 상세 내용이 들어가있으면 리뷰어들이 리뷰하기 한결 더 수월해집니다.
아래 PR을 예시로 형식에 맞는 PR을 주시면 좀 더 좋을 것 같습니다...!! (반드시 하라는게 아니라, 좀 더 수월하게 리뷰가 진행될 수 있다는 의미입니다)

- https://github.com/choorai/retrospect-frontend/pull/2

2024-08-17 20:18 UTC, xi-jjun commented on src/main/java/choorai/retrospect/user/entity/User.java
> +    @Index(name = "idx_user_id", columnList = "user_id", unique = true)
Primary Key를 정의한다면, 자동적으로 clustering index가 생성되고 PK는 unique하기 때문에 해당 설정은 불필요한 것으로 보이는데 확인해주시면 감사하겠습니다.

2024-08-17 20:18 UTC, xi-jjun commented on src/main/resources/db/migration/V240811_1932_create_user.sql
> +    user_id VARCHAR(320) NOT NULL PRIMARY KEY,
석환님께서도 말씀주셨지만, `user_id`와 같이 네이밍하면, 해당 테이블에서의 FK로 오해하기 쉬울 수 있을 것도 같네요.
저는 단순하게 `id`라는 네이밍을 추천드립니다.

2024-08-17 20:18 UTC, xi-jjun commented on src/main/resources/application.yml
> +            sql: trace
해당 로깅의 경우 로컬환경에서 디버깅 용도로 사용하실 것이라면, `application.yml`을 개발환경 용도로 분리해주시는게 적절할 듯 합니다.

2024-08-18 05:30 UTC, xi-jjun requested changes

2024-08-18 05:30 UTC, xi-jjun commented on src/main/resources/db/migration/V240811_1932_create_user.sql
> +    company_name VARCHAR(50) NOT NULL
아무래도 개인 사용자(?)가 있을 경우에 대해서는 기입을 못하는 값일 수도 있을 것 같아요. `department`, `position`, `company_name`은 Nullable하게 하는게 어떨까 싶네요

2024-08-26 15:05 UTC, closed without merging