#5 회고 룸 엔티티 생성
choorai/retrospect-backend pull request #7
Opened 2024-08-13 05:09 UTC by seokhwan-an

## 회고 룸 내 필드 정보
- id
- subject(회고 주제)
- details (회고 상세 내용)
- type (회고 종류)
- time_limit (회고 진행 시간)
- share_link (회고 공유링크)

## 회고 엔티티를 만드면서 고민한 점
현재 회고 룸 안에 share link(회고 공유 링크)를 담고 있는데 share link를 저장할 것이라면 share link도 하나의 테이블로 관리해야할 것 같다는 생각이 들었습니다. 그 이유는 share link가 유효 여부를 db로 관리해서 참가 요청이 들어왔는데 참가가 가능한지 아닌지를 파악해야할 것 같습니다.

2024-08-17 20:25 UTC, xi-jjun requested changes

2024-08-17 20:25 UTC, xi-jjun commented on src/main/java/choorai/retrospect/retrospect_room/Details.java
> +    @Column(name = "details", length = DETAILS_MAX_LENGTH, nullable = false)
DB level에서의 제한보다는 어플리케이션 level에서의 제한으로도 충분할 듯 합니다.
향후 요구사항이 바뀌었을 때 DB alter 작업 보다는 어플리케이션 코드 수정이 더 원활하기 때문입니다.

그리고 현재 아래에 validate가 해당 동작을 대신 수행하기에, 불필요해보이는 설정으로 보입니다.

2024-08-17 20:25 UTC, xi-jjun commented on src/main/java/choorai/retrospect/retrospect_room/Details.java
> +            throw new IllegalArgumentException("회고 상세 내용은 500자 미만이어야 합니다.");
[NIT] 나중에 커스텀 exception 적용하면 좋을 것 같네요 ㅎㅎ

2024-08-17 20:25 UTC, xi-jjun commented on src/main/java/choorai/retrospect/retrospect_room/ShareLink.java
> +    @Column(name = "share_link", length = SHARE_LINK_MAX_LENGTH, nullable = false)
마찬가지로 DB level의 제한은 제거해주심이 더 좋을 듯 합니다.

2024-08-17 20:25 UTC, xi-jjun commented on src/main/resources/db/migration/V20240813_1320__create_retrospect_room.sql
> +    type       ENUM('KPT')  NOT NULL,
[NIT] 이건 호불호 갈리긴한데, 요즘 느끼는 바로써는... enum에 대한 추가/수정/삭제 작업이 많을수록 운영중인 환경에서의 DB alter는 table lock을 걸게되고, 이로써 사용자 요청이 실패할 가능성을 늘리게 됩니다.

그래서 저는 요즘은 varchar로 해서 구별하는 것도 나쁘지 않다고 생각되네요.

2024-08-18 01:25 UTC, seokhwan-an commented on src/main/java/choorai/retrospect/retrospect_room/Details.java
> +    @Column(name = "details", length = DETAILS_MAX_LENGTH, nullable = false)
제가 궁금한게 저는 둘다 제약상황을 적용한 이유가 개발자의 실수(서버의 mysql에서 직접 잘못된 데이터를 넣는 행위) 방지를 위함이었는데 요즘 실무에서는 애플리케이션에서 제약사항을 적용하고 db에는 제약사항을 따로 적용하지 않는 상황인가요??

그러면 이런 상황에서의 실수 방지는 개발자가 db를 통해 데이터를 직접 넣는 권한을 제거하는 방향으로 가나요??

2024-08-18 01:29 UTC, seokhwan-an commented on src/main/java/choorai/retrospect/retrospect_room/Details.java
> +            throw new IllegalArgumentException("회고 상세 내용은 500자 미만이어야 합니다.");
네 이 부분은 민주님이 구현하신 pr이 머지되면 수정할 예정입니다!

2024-08-18 03:00 UTC, xi-jjun commented on src/main/java/choorai/retrospect/retrospect_room/Details.java
> +    @Column(name = "details", length = DETAILS_MAX_LENGTH, nullable = false)
단순 개발자의 실수를 방지하기 위해 넣게되면, 나중에 요구사항이 바뀌어서 길이가 늘어나야 하는 상황에서는 매번 바꿔줘야하는 불편함이 생깁니다.

이 경우 어쩔 수 없이 DB alter작업이 필요하고요. 따라서 DB 제약은 추가하는 것보다 추가하지 않는게 유지보수 시 더 용이해보입니다.

또한 개발자의 어떤 실수가 발생될 것인지도 명확히 알 수 없는 상황이고 사실상 거의 발생하지 않을 것이라 생각됩니다. 

백엔드 차원에서는 유저의 실수에 대해서는 대비하는게 맞으나, 길이와 같은 단순한 문제에 대해서는 개발자의 실수를 고려하지 않아도 좋아 보여요. 
(길이 좀 늘어나서 저장되어도 큰 문제 없음)

2024-08-24 13:47 UTC, JoungMinJu commented on src/main/java/choorai/retrospect/retrospect_room/RetrospectRoom.java
> +    private Time timeLimit;
요기 Date도 추가해야할까요?? 생성시점 + 특정시간 해서 timeLimit에 적어놓자고 전체 회의때 말했던 기억이 있어서요!

2024-08-30 13:06 UTC, JoungMinJu reviewed
짧게 의견 남겨뒀습니다!! 수고하셨습니다 :)

2024-08-30 13:06 UTC, JoungMinJu commented on src/main/java/choorai/retrospect/retrospect_room/entity/RetrospectRoom.java
> +    private Time timeLimit;
RetrospectRoom의 timeLimit에 (생성시점 + 특정시간)을 더한 것을 저장하자는 얘기를 전체회의때 했었는데, 이렇게 구현하려면 이거 DateTime 이어야할 것 같다고 생각하는데 어떻게 생각하시나요??

23시 59분에 생성하고 -> 특정 시간을 더하면 -> 다음날 00시로 저장되어야하는 경우도 있을 것 같아서요!

2024-08-30 13:06 UTC, JoungMinJu commented on src/main/java/choorai/retrospect/retrospect_room/entity/value/Details.java
> +            throw new IllegalArgumentException("회고 상세 내용은 500자 미만이어야 합니다.");
오 생각해보니 제 User는 byte를 기준으로 체크하고있는데 이 부분 추후에 논의해서 맞춰야 할 것 같아요! discussion에 미리 적어놓겠습니다!

2024-09-02 12:25 UTC, JoungMinJu approved these changes

2024-09-02 12:46 UTC, merged